name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main # Hoặc branch bạn dùng để deploy

permissions:
  contents: write # Cần thiết để ghi vào nhánh gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install # Hoặc yarn install nếu dùng yarn

      - name: Build Docusaurus
        run: npm run build # Hoặc yarn build nếu dùng yarn

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
